version: '3'
services:
  rest:
    image: postgrest/postgrest
    container_name: postgrest
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://authenticator:mysecretpassword@{ваш IP адрес}:8432/hadb
      PGRST_DB_SCHEMA: bootcamp
      PGRST_DB_ANON_ROLE: web_anon #In production this role should not be the same as the one used for the connection
      PGRST_SERVER_PROXY_URI: "http://127.0.0.1:3000"
    depends_on:
      - db  
  db:
    container_name: bc_pgsql
    image: postgres:13.1
    environment:
      - DEBUG=false
      - POSTGRES_DB=hadb
      - POSTGRES_USER=ha
      - POSTGRES_PASSWORD=password2021dljfklkla1!kljf;
    volumes:
      - ./postgresql/:/var/lib/postgresql/data
    ports:
      - "8432:5432"
    user: 1000:1000
  webserver:
    image: nginx:mainline-alpine
    container_name: bc_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./http/:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - db
  sftp:
    image: atmoz/sftp
    container_name: bc_sftp
    volumes:
        - ./http/:/home/user/upload
    ports:
        - "2222:22"
    command: user:qwlqfhkllazxcloewkrj:1000
  adminer:
    image: adminer:4.8.0
    container_name: bc_adminer
    restart: always
    depends_on:
      - db
    ports:
      - 9080:8080
    environment:
      ADMINER_DEFAULT_SERVER: 127.0.0.1:8432
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_NAME: hadb
#       ADMINER_PASSWORD: password2021dljfklkla1!kljf;
      ADMINER_USERNAME: ha
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
    volumes:
        - ./adminer/index.php:/var/www/html/index.php

#networks:
#  app-network:
#    driver: bridge
